# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Building Artifacts
  jobs:
   - job: Build
     displayName: Build Artifacts
     pool: Default
     steps:
     - task: Maven@3
       inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
      
     - task: Docker@2 
       displayName: Switch to ansadmin
     - script: su - ansadmin
     - script: ansadmin
     - script: cd /home/azureuser/myagent2/_work/3/s

     - task: Docker@2
       displayName: Run the playbook to create an image and push it to the docker hub
     - script: ansible-playbook -i /etc/ansible/hosts assignment-dockerhub.yaml

     - task: Docker@2
       displayName: Pull the image from the docker hum and create a container on localhost and ec2 server
     - script: ansible-playbook -i /etc/ansible/hosts assignment-useimage.yaml

