# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: container-registry-259614
      IMAGE: eu.gcr.io/container-registry-259614/netent/pac-service

    steps:
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
          version: '318.0.0' # Check the latest release https://cloud.google.com/sdk/docs/release-notes
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_GCR_PUSH_KEY }}
          service_account_email: ${{ secrets.GCP_GCR_PUSH_EMAIL }}
       
    - name: Checkout Pull Request
      uses: actions/checkout@v2
      if: ${{ github.event_name == 'pull_request' }}
      with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.DPE_BOT_GITHUB_PACKAGES_READONLY }}
    
    - name: Checkout Develop
      uses: actions/checkout@v2
      if: ${{ github.event_name == 'push' }}
      with:
          token: ${{ secrets.DPE_BOT_GITHUB_PACKAGES_READONLY }}
              
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Gcloud Docker Auth
      run: gcloud auth configure-docker

      # Build docker image
    - name: Build & Tag Docker Image
      run: docker build -t ${IMAGE}:${GITHUB_SHA::7} .
        
      # Push docker image
    - name: Push to GCR
      run: docker push ${IMAGE}:${GITHUB_SHA::7}

      # Update Tag in GitOps
    - name: GitOps Tag Update
      run: |
          docker run -e "BRANCH_NAME=${GITHUB_REF##*/}" -e "REPO_NAME=${GITHUB_REPOSITORY##*/}" -e "COMMIT_SHA=${GITHUB_SHA}" \
                -e "GITOPS_REPO_NAME=falcon-gitops" -e "SHORT_SHA=${GITHUB_SHA::7}" \
                -e "VALUES_FILE=values.yaml" \
                -e "TAG_FILTER=.deployment.tag" \
                eu.gcr.io/container-registry-259614/dpe-cloud-builders/gitops-tag-updater:stable
